export const personalProjects = [
    {
        id: "uemj-clubs-frontend",
        name: "uemj clubs",
        description: "it is a dynamic emi calculator where it show pie chat of loan amount vs total interest amount. it also allow to download the pie chat.",
        feature: "Search any image\n Infinite Scrolling Effect\n Light & Dark mode\n Can share, copy, download any image\n ",
        technology: ["Next Js", "Next UI", "Redux", "Redux-saga", "Google oAuth2.0", "Node Js", "Express Js", "MongoDB"],
        github: "https://github.com/pradhanDebkanta/uemj-clubs-frontend",
        liveDemo: "https://uemjclubs.vercel.app/",
        img: 'https://imagizer.imageshack.com/img922/4352/Z2cZjU.png',
    },
    {
        id: "order_management_system",
        name: "Order Management System",
        description: "This project is build using Redux, Google oAuth2.0, Ant Design. User only can see dashboard after login with google, and see his/her own profle, can CURD a order.",
        feature: "Search any image\n Infinite Scrolling Effect\n Light & Dark mode\n Can share, copy, download any image\n ",
        technology: ["React", "Redux", "Redux-Saga", "Ant Design", "Google oAuth2.0"],
        github: "https://github.com/pradhanDebkanta/order-management-redux-saga",
        liveDemo: "https://dk-order-managenent.netlify.app/",
        img: 'https://i.postimg.cc/44hVSt1C/order-managenent.png',
        // videoLink: "https://dk-order-managenent.netlify.app/",
    },
    {
        id: "photo_gallery",
        name: "Photo Gallery",
        description: "This app basically searches images from the unsplash api and shows various dimension images with infinite scrolling effect.",
        feature: "Search any image\n Infinite Scrolling Effect\n Light & Dark mode\n Can share, copy, download any image\n ",
        technology: ["React", "Axios",],
        github: "https://github.com/pradhanDebkanta/photo-gallery",
        liveDemo: "https://imggalleryapp.netlify.app/",
        img: 'https://i.postimg.cc/VvRYVDGB/imggalleryapp1.png',
        // videoLink: "https://dk-order-managenent.netlify.app/",
    },
    {
        id: "media_library",
        name: "Media Library",
        description: "This app basically searches images from the unsplash api and shows various dimension images with infinite scrolling effect.",
        feature: "Search any image\n Infinite Scrolling Effect\n Light & Dark mode\n Can share, copy, download any image\n ",
        technology: ["React", "Redux", "Redux-Saga", "Ant Design", "Google oAuth2.0"],
        github: "https://github.com/pradhanDebkanta/media-library",
        liveDemo: "https://medialibraryapp.netlify.app/",
        img: 'https://i.postimg.cc/MTyJwRNP/medialibraryap.png',
        // videoLink: "https://dk-order-managenent.netlify.app/",
    },
    {
        id: "website_template",
        name: "Website Template",
        description: "This app basically searches images from the unsplash api and shows various dimension images with infinite scrolling effect.",
        feature: "It is a frontend page that does not give access for copy any text or content and Right Click is unable for this page.",
        technology: ["JavaScript", "AOS Library", "Bootstrap", "Google map"],
        github: "https://github.com/pradhanDebkanta/website-template",
        liveDemo: "https://pradhandebkanta.github.io/website-template/",
        img: 'https://imagizer.imageshack.com/img922/9373/ei0vH7.png',
        // videoLink: "https://dk-order-managenent.netlify.app/",
    },
    {
        id: "emi_calculator",
        name: "EMI Calculator",
        description: "it is a dynamic emi calculator where it show pie chat of loan amount vs total interest amount. it also allow to download the pie chat.",
        feature: "Search any image\n Infinite Scrolling Effect\n Light & Dark mode\n Can share, copy, download any image\n ",
        technology: ["JavaScript", "HTML5", "CSS3", "Plotly Js", "Bootstrap 4", "Sweet alert",],
        github: "https://github.com/pradhanDebkanta/emicalculator",
        liveDemo: "https://pradhandebkanta.github.io/emicalculator/",
        img: 'https://imagizer.imageshack.com/img924/7056/Zj8MGN.png',
        // videoLink: "https://dk-order-managenent.netlify.app/",
    },
    {
        id: "youtube-ads-blocker",
        name: "youtube ads blocker",
        description: "it is a dynamic emi calculator where it show pie chat of loan amount vs total interest amount. it also allow to download the pie chat.",
        feature: "Search any image\n Infinite Scrolling Effect\n Light & Dark mode\n Can share, copy, download any image\n ",
        technology: ["JavaScript", "HTML5", "CSS3",],
        github: "https://github.com/pradhanDebkanta/youtube-ads-blocker",
        img: 'https://github.com/pradhanDebkanta/youtube-ads-blocker/raw/master/assert/image/step1.png',
    },
    {
        id: "nature_organic",
        name: "Nature Organic",
        description: "it is a dynamic emi calculator where it show pie chat of loan amount vs total interest amount. it also allow to download the pie chat.",
        feature: "Search any image\n Infinite Scrolling Effect\n Light & Dark mode\n Can share, copy, download any image\n ",
        technology: ["React", "Bootstrap 4",],
        github: "https://github.com/pradhanDebkanta/project.protfolio/tree/master",
        liveDemo: "https://pradhandebkanta.github.io/project.protfolio/",
        img: 'https://imagizer.imageshack.com/img924/8630/aGLcwU.png',
        // videoLink: "https://dk-order-managenent.netlify.app/",
    },
    {
        id: "vidyayan",
        name: "Vidyayan",
        description: "it is a dynamic emi calculator where it show pie chat of loan amount vs total interest amount. it also allow to download the pie chat.",
        feature: "Search any image\n Infinite Scrolling Effect\n Light & Dark mode\n Can share, copy, download any image\n ",
        technology: ["React", "Bootstrap 4",],
        github: "https://github.com/pradhanDebkanta/vidyayan/tree/master",
        liveDemo: "https://pradhandebkanta.github.io/vidyayan/",
        img: 'https://imagizer.imageshack.com/img924/189/tW37UR.png',
        // videoLink: "https://dk-order-managenent.netlify.app/",
    },
    {
        id: "upflux",
        name: "upflux",
        description: "it is a dynamic emi calculator where it show pie chat of loan amount vs total interest amount. it also allow to download the pie chat.",
        feature: "Search any image\n Infinite Scrolling Effect\n Light & Dark mode\n Can share, copy, download any image\n ",
        technology: ["React Js",],
        github: "https://github.com/pradhanDebkanta/upflux",
        liveDemo: "https://upflux.netlify.app/",
        img: 'https://imagizer.imageshack.com/img924/89/0LWRvq.png',
    },
    {
        id: "car_driving_game",
        name: "car driving game",
        description: "it is a dynamic emi calculator where it show pie chat of loan amount vs total interest amount. it also allow to download the pie chat.",
        feature: "Search any image\n Infinite Scrolling Effect\n Light & Dark mode\n Can share, copy, download any image\n ",
        technology: ["JavaScript", "HTML5", "CSS3",],
        github: "https://github.com/pradhanDebkanta/cardriving",
        liveDemo: "https://pradhandebkanta.github.io/cardriving/",
        img: 'https://imagizer.imageshack.com/img923/300/MxrhsH.png',
        // videoLink: "https://dk-order-managenent.netlify.app/",
    },
    {
        id: "Brick-Breaker-Paddle-Ball-Game",
        name: "Brick breaker paddle ball game",
        description: "it is a dynamic emi calculator where it show pie chat of loan amount vs total interest amount. it also allow to download the pie chat.",
        feature: "Search any image\n Infinite Scrolling Effect\n Light & Dark mode\n Can share, copy, download any image\n ",
        technology: ["JavaScript", "HTML5", "CSS3",],
        github: "https://github.com/pradhanDebkanta/Brick-Breaker-Paddle-Ball-Game",
        liveDemo: "https://pradhandebkanta.github.io/Brick-Breaker-Paddle-Ball-Game/",
        img: 'https://imagizer.imageshack.com/img924/7140/Xvkv7e.png',
    },
    {
        id: "Neural_Network_in_C++",
        name: "Neural Network in C++",
        description: "it is a dynamic emi calculator where it show pie chat of loan amount vs total interest amount. it also allow to download the pie chat.",
        feature: "Search any image\n Infinite Scrolling Effect\n Light & Dark mode\n Can share, copy, download any image\n ",
        technology: ["C++",],
        github: "https://github.com/pradhanDebkanta/neuralNetwork",
        img: 'https://1.cms.s81c.com/sites/default/files/2021-01-06/ICLH_Diagram_Batch_01_03-DeepNeuralNetwork-WHITEBG.png',
    },
    {
        id: "tetris_game",
        name: "Tetris Game",
        description: "This Tetris game is made using C programing.",
        feature: "Search any image\n Infinite Scrolling Effect\n Light & Dark mode\n Can share, copy, download any image\n ",
        technology: ["C language",],
        github: "https://github.com/pradhanDebkanta/tetris-game",
        img: 'https://imagizer.imageshack.com/img924/81/5azkmB.png',
        // videoLink: "https://dk-order-managenent.netlify.app/",
    },
    {
        id: "Smart_Room_Cleaner_Robot",
        name: "Smart Room Cleaner Robot",
        description: "it is a dynamic emi calculator where it show pie chat of loan amount vs total interest amount. it also allow to download the pie chat.",
        feature: "Search any image\n Infinite Scrolling Effect\n Light & Dark mode\n Can share, copy, download any image\n ",
        technology: ["Arduino Uno",],
        github: "https://github.com/pradhanDebkanta/smart-room-cleaner-robot",
        img: 'https://imagizer.imageshack.com/img924/89/0LWRvq.png',
    },
    {
        id: "Smart_Water_Tank",
        name: "Smart Water Tank",
        description: "it is a dynamic emi calculator where it show pie chat of loan amount vs total interest amount. it also allow to download the pie chat.",
        feature: "Search any image\n Infinite Scrolling Effect\n Light & Dark mode\n Can share, copy, download any image\n ",
        technology: ["Arduino Uno",],
        github: "https://github.com/pradhanDebkanta/smart-water-tank",
        img: 'https://imagizer.imageshack.com/img923/2642/CavnWz.png',
    },
];

export const contributeProject = [
    {
        id: "wishlist_app",
        name: "Wishlist App",
        description: "",
        feature: "",
        contribution: "",
        technology: ["Next Js", "Shopify", "Shopify App bridge", "Polaris", "Chakra UI"],
        liveDemo: "https://apps.shopify.com/z08-wishlist-app"
    },
    {
        id: "size-chart-app",
        name: "Size Chart App",
        description: "",
        feature: "",
        contribution: "",
        technology: ["Next Js", "Shopify", "Shopify App bridge", "Polaris", "Chakra UI"],
        liveDemo: "https://apps.shopify.com/z08-size-chart-app"
    },
    {
        id: "heatmap-app",
        name: "Heatmap App",
        description: "",
        feature: "",
        contribution: "",
        technology: ["Next Js", "Shopify", "Shopify App bridge", "Chakra UI", "Ant Design"],
        liveDemo: "https://apps.shopify.com/z08-heatmap-app"
    },
    {
        id: "heatmap-app",
        name: "Heatmap App",
        description: "",
        feature: "",
        contribution: "",
        technology: ["React Js", "Redux", "Meterial UI", "Bootstrap 4", "Node Js", "Express Js", "MongoDB",],
        liveDemo: "https://vidyayan.in/"
    },
]
