import Head from 'next/head'
import Image from 'next/image'
import { useTheme as useNextTheme } from 'next-themes'
import { Switch, useTheme } from '@nextui-org/react'

export default function Home() {
  const { setTheme } = useNextTheme();
  const { isDark, type } = useTheme();
  return (
    <div className=''>
      <Head>
        <title>Debkanta Pradhan&#39;s portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href='/profile.png' />
      </Head>
      <div>
       
        <div>
          The current theme is: {type}
          <Switch
            checked={isDark}
            onChange={(e) => setTheme(e.target.checked ? 'dark' : 'light')}
          />
        </div>
      </div>
    </div>
  )
}
