import Head from 'next/head'
import Image from 'next/image'
import { useTheme as useNextTheme } from 'next-themes'
import { useTheme } from '@nextui-org/react'

export default function Home() {
  const { setTheme } = useNextTheme();
  const { isDark, type } = useTheme();
  return (
    <div className=''>
      <Head>
        <title>Debkanta Pradhan&#39;s portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href='/profile.png' />
      </Head>
      <div>

        <div>
          <div id='home'
            style={{
              minHeight: '800px'
            }}
          >
            When user interacts with the argument element outside of the overlay ref, return true if onClose should be called. This gives you a chance to filter out interaction with elements that should not dismiss the overlay. By default, onClose will always be called on interaction outside the overlay ref.
          </div>
          <div id='skills'
            style={{
              minHeight: '800px'
            }}
          >
            When user interacts with the argument element outside of the overlay ref, return true if onClose should be called. This gives you a chance to filter out interaction with elements that should not dismiss the overlay. By default, onClose will always be called on interaction outside the overlay ref.
          </div>
          <div id='experience'
            style={{
              minHeight: '800px'
            }}
          >
            When user interacts with the argument element outside of the overlay ref, return true if onClose should be called. This gives you a chance to filter out interaction with elements that should not dismiss the overlay. By default, onClose will always be called on interaction outside the overlay ref.
          </div>


        </div>
      </div>
    </div>
  )
}
