export const personalProjects = [
    {
        id: "uemj-clubs-frontend",
        name: "uemj clubs",
        description: "It is a platform where we bring all the clubs into a single platform. Collage higher authority can assign faculty co-ordinator amoung the faculty for each and every club. Student have to pre-register using google form for join the clubs. Later student can permited to join the clubs using same details. All the students data are fetched from the google sheet. Student can send request for sudent co-ordinator for a perticular club. Faculty Co-ordinator can allow or deny the request. Faculty & Student Co-ordinator can organize events in this platform. All the activity are recorded in this platform. Faculty Co-ordinator can broadcast or unicast any information among the members.",
        feature: "All the clubs in our collage are bring into a single platform.\n There are 3 section in this platform i) Student member. \tii) Faculty co-ordinator & Student Co-ordinator.\tiii) Administrator.\n Administrator have to valid authorized first.\n Administrator can assign Faculty co-ordinator for each & every club.\n Interested Student have to fill there academic details in a google form as a pre-registration process.\n Later Students accademic details are fetched from google sheet & allow to make a profile on this platform & can join any club.\n Enthusiastic student can request for co-ordinator of his registered club.\n Co-ordinators can organized an events and broadcast among the members.\n All events are recorded in this platform.\n Individual student activity & award are recorded in this platform.",
        technology: ["Next Js", "Next UI", "Redux", "Redux-saga", "Formik & Yup", "Google oAuth2.0", "Node Js", "Express Js", "MongoDB"],
        github: "https://github.com/pradhanDebkanta/uemj-clubs-frontend",
        liveDemo: "https://uemjclubs.vercel.app/",
        img: 'https://imagizer.imageshack.com/img922/4352/Z2cZjU.png',
    },
    {
        id: "order_management_system",
        name: "Order Management System",
        description: "This app basically record the order & customer details. User can only access the dashboard after login. User create an new order, edit, delete an order details.",
        feature: "SignIn with Google oAuth.\n User only can see dashboard & profile after login.\n User can create a new order, edit an existing order, delete a order.",
        technology: ["React", "Redux", "Redux-Saga", "Ant Design", "Google oAuth2.0"],
        github: "https://github.com/pradhanDebkanta/order-management-redux-saga",
        liveDemo: "https://dk-order-managenent.netlify.app/",
        img: 'https://i.postimg.cc/44hVSt1C/order-managenent.png',
        // videoLink: "https://dk-order-managenent.netlify.app/",
    },
    {
        id: "photo_gallery",
        name: "Photo Gallery",
        description: "This app basically searches images from the unsplash api and shows various dimension images with infinite scrolling effect.",
        feature: "Search a image by name.\nImages are fetched from the unsplash.\nShow the images according it's individual size.\n Infinite Scrolling Effect like Youtube.\n Light & Dark theme mode.\n Can share, copy, download a image.",
        technology: ["React", "Axios",],
        github: "https://github.com/pradhanDebkanta/photo-gallery",
        liveDemo: "https://imggalleryapp.netlify.app/",
        img: 'https://i.postimg.cc/VvRYVDGB/imggalleryapp1.png',
        // videoLink: "https://dk-order-managenent.netlify.app/",
    },
    {
        id: "media_library",
        name: "Media Library",
        description: "This app basically create a collection of different type of media. User can only access the media dashboard after login. User later on can play his collection.",
        feature: "SignIn with Google oAuth.\n User only can see the media collection after login.\n User can categories the media and store media by it's url.\n User can play that media and keep a watch history of that.",
        technology: ["React", "Redux", "Redux-Saga", "Ant Design", "Google oAuth2.0"],
        github: "https://github.com/pradhanDebkanta/media-library",
        liveDemo: "https://medialibraryapp.netlify.app/",
        img: 'https://i.postimg.cc/MTyJwRNP/medialibraryap.png',
        // videoLink: "https://dk-order-managenent.netlify.app/",
    },
    {
        id: "website_template",
        name: "Website Template",
        description: "It is a frontend page with smooth animation that does not give access for copy any text or content and disable right click for this page.",
        feature: "Smooth animation effect.\n Disable right click.\n Prevent to copy any text or content.",
        technology: ["JavaScript", "AOS Library", "Bootstrap", "Google map"],
        github: "https://github.com/pradhanDebkanta/website-template",
        liveDemo: "https://pradhandebkanta.github.io/website-template/",
        img: 'https://imagizer.imageshack.com/img922/9373/ei0vH7.png',
        // videoLink: "https://dk-order-managenent.netlify.app/",
    },
    {
        id: "emi_calculator",
        name: "EMI Calculator",
        description: "it is a dynamic emi calculator where it calculate the simple interest & show pie chat of loan amount vs total interest amount. it also allow to download the pie chat.",
        feature: "Calculate EMI of each type of loan like home loan, education loan, car loan.\n Show each month EMI amount in table format.\n Show pie chart of interest & principal.",
        technology: ["JavaScript", "HTML5", "CSS3", "Plotly Js", "Bootstrap 4", "Sweet alert",],
        github: "https://github.com/pradhanDebkanta/emicalculator",
        liveDemo: "https://pradhandebkanta.github.io/emicalculator/",
        img: 'https://imagizer.imageshack.com/img924/7056/Zj8MGN.png',
        // videoLink: "https://dk-order-managenent.netlify.app/",
    },
    {
        id: "youtube-ads-blocker",
        name: "youtube ads blocker",
        description: "This is a youtube ads blocker extension, that block all ads.",
        feature: "This chrome extension only work for youtube.\n It skip the ads on youtube.\n It also block all types of promotion ads and vedio that is unnecessary.",
        technology: ["JavaScript", "HTML5", "CSS3",],
        github: "https://github.com/pradhanDebkanta/youtube-ads-blocker",
        img: 'https://github.com/pradhanDebkanta/youtube-ads-blocker/raw/master/assert/image/step1.png',
    },
    {
        id: "nature_organic",
        name: "Nature Organic",
        description: "It's a simple frontend template with awesome animation.",
        feature: "It's a simple frontend template with awesome animation & hover effect.",
        technology: ["React", "Bootstrap 4",],
        github: "https://github.com/pradhanDebkanta/project.protfolio/tree/master",
        liveDemo: "https://pradhandebkanta.github.io/project.protfolio/",
        img: 'https://imagizer.imageshack.com/img924/8630/aGLcwU.png',
        // videoLink: "https://dk-order-managenent.netlify.app/",
    },
    {
        id: "vidyayan",
        name: "Vidyayan",
        description: "It's a simple frontend template with awesome animation.",
        feature: "It's a simple frontend template with awesome animation & hover effect.",
        technology: ["React", "Bootstrap 4",],
        github: "https://github.com/pradhanDebkanta/vidyayan/tree/master",
        liveDemo: "https://pradhandebkanta.github.io/vidyayan/",
        img: 'https://imagizer.imageshack.com/img924/189/tW37UR.png',
        // videoLink: "https://dk-order-managenent.netlify.app/",
    },
    {
        id: "upflux",
        name: "upflux",
        description: "It's a simple frontend template with awesome animation.",
        feature: "It's a simple frontend template with awesome animation & hover effect.",
        technology: ["React Js",],
        github: "https://github.com/pradhanDebkanta/upflux",
        liveDemo: "https://upflux.netlify.app/",
        img: 'https://imagizer.imageshack.com/img924/89/0LWRvq.png',
    },
    {
        id: "car_driving_game",
        name: "car driving game",
        description: "This is a browser game. Player have to drive his car without collide any car.",
        feature: "Player have to drive his car without collide any opinion car.\n Player can move his car easily by left, right, up & down key.\n It's fully responsive and can easily play in mobile browser.\n Player can give horn and can also mute himself.",
        technology: ["JavaScript", "HTML5", "CSS3",],
        github: "https://github.com/pradhanDebkanta/cardriving",
        liveDemo: "https://pradhandebkanta.github.io/cardriving/",
        img: 'https://imagizer.imageshack.com/img923/300/MxrhsH.png',
        // videoLink: "https://dk-order-managenent.netlify.app/",
    },
    {
        id: "Brick-Breaker-Paddle-Ball-Game",
        name: "Brick breaker paddle ball game",
        description: "This is a browser game. Player have to bounce the ball on the paddle and break the brick without droping the ball from the paddle.",
        feature: "Player have to bounce the ball on the paddle without droping the ball from the paddle.\n Player have given 3 chance to bounce the ball on paddle after failing the ball ouside from paddle.\n It's fully responsive and can easily play in mobile browser.",
        technology: ["JavaScript", "HTML5", "CSS3",],
        github: "https://github.com/pradhanDebkanta/Brick-Breaker-Paddle-Ball-Game",
        liveDemo: "https://pradhandebkanta.github.io/Brick-Breaker-Paddle-Ball-Game/",
        img: 'https://imagizer.imageshack.com/img924/7140/Xvkv7e.png',
    },
    {
        id: "Neural_Network_in_C++",
        name: "Neural Network in C++",
        description: "",
        feature: "",
        technology: ["C++",],
        github: "https://github.com/pradhanDebkanta/neuralNetwork",
        img: 'https://1.cms.s81c.com/sites/default/files/2021-01-06/ICLH_Diagram_Batch_01_03-DeepNeuralNetwork-WHITEBG.png',
    },
    {
        id: "tetris_game",
        name: "Tetris Game",
        description: "This Tetris game is made using C programing.",
        feature: "This tetris game is similar to others tetris game.\n It give the next block diagram in advance.\n Player have to arrange the block so that all the entired row fulfilled by blocked.\n Heighest score will store for future.",
        technology: ["C language",],
        github: "https://github.com/pradhanDebkanta/tetris-game",
        img: 'https://imagizer.imageshack.com/img924/81/5azkmB.png',
        // videoLink: "https://dk-order-managenent.netlify.app/",
    },
    {
        id: "Smart_Room_Cleaner_Robot",
        name: "Smart Room Cleaner Robot",
        description: "",
        feature: "",
        technology: ["Arduino Uno",],
        github: "https://github.com/pradhanDebkanta/smart-room-cleaner-robot",
        img: 'https://imagizer.imageshack.com/img924/89/0LWRvq.png',
    },
    {
        id: "Smart_Water_Tank",
        name: "Smart Water Tank",
        description: "Smart Water Tank is a tank that start the water pump when the water level is gone down. It also show the water uses reading on LCD display and indicate the water level.",
        feature: "Automatically power on the water pump when the water level of the tank is gone down and power off the water pump when the tank get full with help of relay module.\n Show the water volume on LCD display.\n show the amount of water uses daily.\n It also show the led indicator outside the tank.",
        technology: ["Arduino Uno",],
        github: "https://github.com/pradhanDebkanta/smart-water-tank",
        img: 'https://imagizer.imageshack.com/img923/2642/CavnWz.png',
    },
];

export const contributeProject = [
    {
        id: "wishlist_app",
        name: "Wishlist App",
        description: "Wishlist app is a shopify app that is available on shopify store. ",
        feature: "",
        contribution: "",
        technology: ["Next Js", "Shopify", "Shopify App bridge", "Polaris", "Chakra UI"],
        liveDemo: "https://apps.shopify.com/z08-wishlist-app"
    },
    {
        id: "size-chart-app",
        name: "Size Chart App",
        description: "Size Chart app is a shopify app that is available on shopify store.",
        feature: "",
        contribution: "",
        technology: ["Next Js", "Shopify", "Shopify App bridge", "Polaris", "Chakra UI"],
        liveDemo: "https://apps.shopify.com/z08-size-chart-app"
    },
    {
        id: "heatmap-app",
        name: "Heatmap App",
        description: "Heatmap app is a shopify app that is available on shopify store.",
        feature: "",
        contribution: "",
        technology: ["Next Js", "Shopify", "Shopify App bridge", "Chakra UI", "Ant Design"],
        liveDemo: "https://apps.shopify.com/z08-heatmap-app"
    },
    {
        id: "vidyayan-app",
        name: "Vidyayan - Online Live, Coding, Home Tutor ",
        description: "The Vidyayan is a well-known EdTech organization. Vidyayan is the tutor providing platform that connects students searching for a tutor with tutors looking to generate additional income. Vidyayan features India's best home and online tutors, ranked and reviewed by students. We aim to openly identify India's best tutors, and have them constantly prove their excellence by getting top reviews from students.",
        feature: "Students can search for a tutor and send a request to the tutor.\n Tutor can see the students and accept or deny the students request.\n All the things can be monitored by the admin dashboard.\n Students can access online classroom, library, live, past, upcoming classes on their dashboard.\n Tutors can create a classroom, live classes, class-test, exam and send study materials to students.\n All are tracked by Admin dashboard and admin can allow or block students and also tutor.",
        contribution: "I had built student, tutor, admin dashboard.\n I build online examination platform.\n I build classroom and library platform.\n Build Student, Tutor, Admin profile sectonalso.\n I build all the things using React, Redux and integrate API with backend and build some API end-point also. ",
        technology: ["React Js", "Redux", "Meterial UI", "Bootstrap 4", "Node Js", "Express Js", "MongoDB",],
        liveDemo: "https://vidyayan.in/"
    },
]
